program e_docs_api_swagger;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Horse.GBSwagger,
  dmfbr.validation.pipe,
  dmfbr.modular,
  horse.modular,
  nfe.controller.swagger in 'swagger\nfe\nfe.controller.swagger.pas',
  config.controller.swagger in 'swagger\empresa\config.controller.swagger.pas',
  xml.controller.swagger in 'swagger\xml\xml.controller.swagger.pas',
  pdf.controller.swagger in 'swagger\pdf\pdf.controller.swagger.pas',
  core.include in 'swagger\core\core.include.pas',
  endereco.model in 'modulos\core\models\endereco.model.pas',
  nfebr.model in 'nfebrlib\models\nfebr.model.pas',
  nfebr.request.cancela.consulta in 'nfebrlib\requests\nfebr.request.cancela.consulta.pas',
  nfebr.request.cancela in 'nfebrlib\requests\nfebr.request.cancela.pas',
  nfebr.request.cce.consulta in 'nfebrlib\requests\nfebr.request.cce.consulta.pas',
  nfebr.request.cce in 'nfebrlib\requests\nfebr.request.cce.pas',
  nfebr.request.consulta.lote in 'nfebrlib\requests\nfebr.request.consulta.lote.pas',
  nfebr.request.consulta in 'nfebrlib\requests\nfebr.request.consulta.pas',
  nfebr.request.inutiliza.consulta in 'nfebrlib\requests\nfebr.request.inutiliza.consulta.pas',
  nfebr.request.inutiliza in 'nfebrlib\requests\nfebr.request.inutiliza.pas',
  nfebr.request.transmite in 'nfebrlib\requests\nfebr.request.transmite.pas',
  nfebr.response.cancela.consulta in 'nfebrlib\responses\nfebr.response.cancela.consulta.pas',
  nfebr.response.cancela in 'nfebrlib\responses\nfebr.response.cancela.pas',
  nfebr.response.cce.consulta in 'nfebrlib\responses\nfebr.response.cce.consulta.pas',
  nfebr.response.cce in 'nfebrlib\responses\nfebr.response.cce.pas',
  nfebr.response.consulta in 'nfebrlib\responses\nfebr.response.consulta.pas',
  nfebr.response.inutiliza in 'nfebrlib\responses\nfebr.response.inutiliza.pas',
  nfebr.response.servicostatus in 'nfebrlib\responses\nfebr.response.servicostatus.pas',
  nfebr.response.transmite.lote in 'nfebrlib\responses\nfebr.response.transmite.lote.pas',
  nfebr.response.transmite in 'nfebrlib\responses\nfebr.response.transmite.pas',
  nfebr.config in 'nfebrlib\models\nfebr.config.pas',
  nfebr.constantes in 'nfebrlib\models\nfebr.constantes.pas',
  nfebr.response.base in 'nfebrlib\responses\nfebr.response.base.pas',
  nfebr.tag.adi.model in 'nfebrlib\models\tags\nfebr.tag.adi.model.pas',
  nfebr.tag.arma.model in 'nfebrlib\models\tags\nfebr.tag.arma.model.pas',
  nfebr.tag.autxml.model in 'nfebrlib\models\tags\nfebr.tag.autxml.model.pas',
  nfebr.tag.avulsa.model in 'nfebrlib\models\tags\nfebr.tag.avulsa.model.pas',
  nfebr.tag.cana.model in 'nfebrlib\models\tags\nfebr.tag.cana.model.pas',
  nfebr.tag.card.model in 'nfebrlib\models\tags\nfebr.tag.card.model.pas',
  nfebr.tag.cide.model in 'nfebrlib\models\tags\nfebr.tag.cide.model.pas',
  nfebr.tag.cobr.model in 'nfebrlib\models\tags\nfebr.tag.cobr.model.pas',
  nfebr.tag.cofins.model in 'nfebrlib\models\tags\nfebr.tag.cofins.model.pas',
  nfebr.tag.cofinsaliq.model in 'nfebrlib\models\tags\nfebr.tag.cofinsaliq.model.pas',
  nfebr.tag.cofinsoutr.model in 'nfebrlib\models\tags\nfebr.tag.cofinsoutr.model.pas',
  nfebr.tag.cofinsqtde.model in 'nfebrlib\models\tags\nfebr.tag.cofinsqtde.model.pas',
  nfebr.tag.cofinsst.model in 'nfebrlib\models\tags\nfebr.tag.cofinsst.model.pas',
  nfebr.tag.comb.model in 'nfebrlib\models\tags\nfebr.tag.comb.model.pas',
  nfebr.tag.compra.model in 'nfebrlib\models\tags\nfebr.tag.compra.model.pas',
  nfebr.tag.deduc.model in 'nfebrlib\models\tags\nfebr.tag.deduc.model.pas',
  nfebr.tag.dest.model in 'nfebrlib\models\tags\nfebr.tag.dest.model.pas',
  nfebr.tag.det.model in 'nfebrlib\models\tags\nfebr.tag.det.model.pas',
  nfebr.tag.detexport.model in 'nfebrlib\models\tags\nfebr.tag.detexport.model.pas',
  nfebr.tag.detpag.model in 'nfebrlib\models\tags\nfebr.tag.detpag.model.pas',
  nfebr.tag.di.model in 'nfebrlib\models\tags\nfebr.tag.di.model.pas',
  nfebr.tag.dup.model in 'nfebrlib\models\tags\nfebr.tag.dup.model.pas',
  nfebr.tag.emit.model in 'nfebrlib\models\tags\nfebr.tag.emit.model.pas',
  nfebr.tag.encerrante.model in 'nfebrlib\models\tags\nfebr.tag.encerrante.model.pas',
  nfebr.tag.enderdest.model in 'nfebrlib\models\tags\nfebr.tag.enderdest.model.pas',
  nfebr.tag.enderemit.model in 'nfebrlib\models\tags\nfebr.tag.enderemit.model.pas',
  nfebr.tag.entrega.model in 'nfebrlib\models\tags\nfebr.tag.entrega.model.pas',
  nfebr.tag.exporta.model in 'nfebrlib\models\tags\nfebr.tag.exporta.model.pas',
  nfebr.tag.exportind.model in 'nfebrlib\models\tags\nfebr.tag.exportind.model.pas',
  nfebr.tag.fat.model in 'nfebrlib\models\tags\nfebr.tag.fat.model.pas',
  nfebr.tag.fordia.model in 'nfebrlib\models\tags\nfebr.tag.fordia.model.pas',
  nfebr.tag.icms.model in 'nfebrlib\models\tags\nfebr.tag.icms.model.pas',
  nfebr.tag.icms00.model in 'nfebrlib\models\tags\nfebr.tag.icms00.model.pas',
  nfebr.tag.icms02.model in 'nfebrlib\models\tags\nfebr.tag.icms02.model.pas',
  nfebr.tag.icms10.model in 'nfebrlib\models\tags\nfebr.tag.icms10.model.pas',
  nfebr.tag.icms15.model in 'nfebrlib\models\tags\nfebr.tag.icms15.model.pas',
  nfebr.tag.icms20.model in 'nfebrlib\models\tags\nfebr.tag.icms20.model.pas',
  nfebr.tag.icms30.model in 'nfebrlib\models\tags\nfebr.tag.icms30.model.pas',
  nfebr.tag.icms40.model in 'nfebrlib\models\tags\nfebr.tag.icms40.model.pas',
  nfebr.tag.icms51.model in 'nfebrlib\models\tags\nfebr.tag.icms51.model.pas',
  nfebr.tag.icms53.model in 'nfebrlib\models\tags\nfebr.tag.icms53.model.pas',
  nfebr.tag.icms60.model in 'nfebrlib\models\tags\nfebr.tag.icms60.model.pas',
  nfebr.tag.icms61.model in 'nfebrlib\models\tags\nfebr.tag.icms61.model.pas',
  nfebr.tag.icms70.model in 'nfebrlib\models\tags\nfebr.tag.icms70.model.pas',
  nfebr.tag.icms90.model in 'nfebrlib\models\tags\nfebr.tag.icms90.model.pas',
  nfebr.tag.icmscomb.model in 'nfebrlib\models\tags\nfebr.tag.icmscomb.model.pas',
  nfebr.tag.icmscons.model in 'nfebrlib\models\tags\nfebr.tag.icmscons.model.pas',
  nfebr.tag.icmsinter.model in 'nfebrlib\models\tags\nfebr.tag.icmsinter.model.pas',
  nfebr.tag.icmspart.model in 'nfebrlib\models\tags\nfebr.tag.icmspart.model.pas',
  nfebr.tag.icmssn101.model in 'nfebrlib\models\tags\nfebr.tag.icmssn101.model.pas',
  nfebr.tag.icmssn102.model in 'nfebrlib\models\tags\nfebr.tag.icmssn102.model.pas',
  nfebr.tag.icmssn201.model in 'nfebrlib\models\tags\nfebr.tag.icmssn201.model.pas',
  nfebr.tag.icmssn202.model in 'nfebrlib\models\tags\nfebr.tag.icmssn202.model.pas',
  nfebr.tag.icmssn500.model in 'nfebrlib\models\tags\nfebr.tag.icmssn500.model.pas',
  nfebr.tag.icmssn900.model in 'nfebrlib\models\tags\nfebr.tag.icmssn900.model.pas',
  nfebr.tag.icmsst.model in 'nfebrlib\models\tags\nfebr.tag.icmsst.model.pas',
  nfebr.tag.icmstot.model in 'nfebrlib\models\tags\nfebr.tag.icmstot.model.pas',
  nfebr.tag.icmsufdest.model in 'nfebrlib\models\tags\nfebr.tag.icmsufdest.model.pas',
  nfebr.tag.ide.model in 'nfebrlib\models\tags\nfebr.tag.ide.model.pas',
  nfebr.tag.ii.model in 'nfebrlib\models\tags\nfebr.tag.ii.model.pas',
  nfebr.tag.imposto.model in 'nfebrlib\models\tags\nfebr.tag.imposto.model.pas',
  nfebr.tag.impostodevol.model in 'nfebrlib\models\tags\nfebr.tag.impostodevol.model.pas',
  nfebr.tag.infadic.model in 'nfebrlib\models\tags\nfebr.tag.infadic.model.pas',
  nfebr.tag.infintermed.model in 'nfebrlib\models\tags\nfebr.tag.infintermed.model.pas',
  nfebr.tag.infnfe.model in 'nfebrlib\models\tags\nfebr.tag.infnfe.model.pas',
  nfebr.tag.infnfesupl.model in 'nfebrlib\models\tags\nfebr.tag.infnfesupl.model.pas',
  nfebr.tag.infprodemb.model in 'nfebrlib\models\tags\nfebr.tag.infprodemb.model.pas',
  nfebr.tag.infprodnff.model in 'nfebrlib\models\tags\nfebr.tag.infprodnff.model.pas',
  nfebr.tag.infresptec.model in 'nfebrlib\models\tags\nfebr.tag.infresptec.model.pas',
  nfebr.tag.infsolicnff.model in 'nfebrlib\models\tags\nfebr.tag.infsolicnff.model.pas',
  nfebr.tag.infsupl.model in 'nfebrlib\models\tags\nfebr.tag.infsupl.model.pas',
  nfebr.tag.ipi.model in 'nfebrlib\models\tags\nfebr.tag.ipi.model.pas',
  nfebr.tag.issqn.model in 'nfebrlib\models\tags\nfebr.tag.issqn.model.pas',
  nfebr.tag.issqntot.model in 'nfebrlib\models\tags\nfebr.tag.issqntot.model.pas',
  nfebr.tag.lacre.model in 'nfebrlib\models\tags\nfebr.tag.lacre.model.pas',
  nfebr.tag.med.model in 'nfebrlib\models\tags\nfebr.tag.med.model.pas',
  nfebr.tag.nfref.model in 'nfebrlib\models\tags\nfebr.tag.nfref.model.pas',
  nfebr.tag.obscont.model in 'nfebrlib\models\tags\nfebr.tag.obscont.model.pas',
  nfebr.tag.obsfisco.model in 'nfebrlib\models\tags\nfebr.tag.obsfisco.model.pas',
  nfebr.tag.obsitem.model in 'nfebrlib\models\tags\nfebr.tag.obsitem.model.pas',
  nfebr.tag.origcomb.model in 'nfebrlib\models\tags\nfebr.tag.origcomb.model.pas',
  nfebr.tag.pag.model in 'nfebrlib\models\tags\nfebr.tag.pag.model.pas',
  nfebr.tag.pis.model in 'nfebrlib\models\tags\nfebr.tag.pis.model.pas',
  nfebr.tag.pisaliq.model in 'nfebrlib\models\tags\nfebr.tag.pisaliq.model.pas',
  nfebr.tag.pisoutr.model in 'nfebrlib\models\tags\nfebr.tag.pisoutr.model.pas',
  nfebr.tag.pisqtde.model in 'nfebrlib\models\tags\nfebr.tag.pisqtde.model.pas',
  nfebr.tag.pisst.model in 'nfebrlib\models\tags\nfebr.tag.pisst.model.pas',
  nfebr.tag.procref.model in 'nfebrlib\models\tags\nfebr.tag.procref.model.pas',
  nfebr.tag.prod.model in 'nfebrlib\models\tags\nfebr.tag.prod.model.pas',
  nfebr.tag.rastro.model in 'nfebrlib\models\tags\nfebr.tag.rastro.model.pas',
  nfebr.tag.reboque.model in 'nfebrlib\models\tags\nfebr.tag.reboque.model.pas',
  nfebr.tag.refecf.model in 'nfebrlib\models\tags\nfebr.tag.refecf.model.pas',
  nfebr.tag.refnf.model in 'nfebrlib\models\tags\nfebr.tag.refnf.model.pas',
  nfebr.tag.refnfp.model in 'nfebrlib\models\tags\nfebr.tag.refnfp.model.pas',
  nfebr.tag.retirada.model in 'nfebrlib\models\tags\nfebr.tag.retirada.model.pas',
  nfebr.tag.rettransp.model in 'nfebrlib\models\tags\nfebr.tag.rettransp.model.pas',
  nfebr.tag.rettrib.model in 'nfebrlib\models\tags\nfebr.tag.rettrib.model.pas',
  nfebr.tag.total.model in 'nfebrlib\models\tags\nfebr.tag.total.model.pas',
  nfebr.tag.transp.model in 'nfebrlib\models\tags\nfebr.tag.transp.model.pas',
  nfebr.tag.transporta.model in 'nfebrlib\models\tags\nfebr.tag.transporta.model.pas',
  nfebr.tag.veicprod.model in 'nfebrlib\models\tags\nfebr.tag.veicprod.model.pas',
  nfebr.tag.veictransp.model in 'nfebrlib\models\tags\nfebr.tag.veictransp.model.pas',
  nfebr.tag.vol.model in 'nfebrlib\models\tags\nfebr.tag.vol.model.pas',
  app.route in 'modulos\app.route.pas',
  app.module in 'modulos\app.module.pas',
  config.module in 'modulos\config\config.module.pas',
  config.route.handler in 'modulos\config\config.route.handler.pas',
  config.controller in 'modulos\config\controllers\config.controller.pas',
  config.infra in 'modulos\config\infras\config.infra.pas',
  config.interfaces in 'modulos\config\interfaces\config.interfaces.pas',
  config.repository in 'modulos\config\repositories\config.repository.pas',
  config.service in 'modulos\config\services\config.service.pas',
  core.constantes in 'modulos\core\core.constantes.pas',
  core.exception in 'modulos\core\core.exception.pas',
  core.types in 'modulos\core\core.types.pas',
  core.module in 'modulos\core\core.module.pas',
  nfebr.lib.json in 'nfebrlib\nfebr.lib.json.pas',
  nfebr.lib.nfe in 'nfebrlib\nfebr.lib.nfe.pas',
  nfebr.lib.enum in 'nfebrlib\core\nfebr.lib.enum.pas',
  nfebr.lib.include in 'nfebrlib\core\nfebr.lib.include.pas',
  nfebr.lib.utils in 'nfebrlib\core\nfebr.lib.utils.pas',
  nfebr.lib.jsonbr in 'nfebrlib\implementations\jsonbr\nfebr.lib.jsonbr.pas',
  nfebr.lib.acbr in 'nfebrlib\implementations\nfeacbr\nfebr.lib.acbr.pas';

var
  LRotas: TRotas;
begin
  // Swagger
  THorse.Use(HorseSwagger);
  // Registrando o AppModule
  THorse.Use(HorseModular(TAppModule.Create));

  // Use ValidationPipe
  Modular.UsePipes(TValidationPipe.Create);

  Swagger.Info.Title('API Nota Fiscal')
              .Description('API para emissão de notas fiscais.')
              .Contact.Name('Isaque Pinheiro')
                      .Email('isaquesp@email.com.br')
                      .URL('https://www.isaquepinheiro.com.br')
              .&End
         .&End
         .BasePath(LRotas.Root);
  THorse.Listen(9001, '127.0.0.1',
    procedure
    begin
      Writeln(Format('Servidor no ar Porta: %s, acesso em %s', ['9001', 'http://localhost:9001/swagger/doc/html#']));
    end);
end.
